CREATE TABLE Branches (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(160) NOT NULL,
    City NVARCHAR(120) NOT NULL,
    EmergencyPhone NVARCHAR(40) NOT NULL
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FullName NVARCHAR(180) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Role NVARCHAR(40) NOT NULL,
    BranchId UNIQUEIDENTIFIER NULL REFERENCES Branches(Id),
    PasswordHash NVARCHAR(512) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE Patients (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    MedicalRecordNumber NVARCHAR(40) NOT NULL UNIQUE,
    FullName NVARCHAR(180) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Phone NVARCHAR(40) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL REFERENCES Branches(Id),
    InsuranceProvider NVARCHAR(160) NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE Doctors (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FullName NVARCHAR(180) NOT NULL,
    Specialty NVARCHAR(120) NOT NULL,
    BranchId UNIQUEIDENTIFIER NOT NULL REFERENCES Branches(Id),
    SupportsVideoConsultation BIT NOT NULL
);

CREATE TABLE Appointments (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PatientId UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL REFERENCES Doctors(Id),
    BranchId UNIQUEIDENTIFIER NOT NULL REFERENCES Branches(Id),
    StartsAt DATETIMEOFFSET NOT NULL,
    EndsAt DATETIMEOFFSET NOT NULL,
    IsVideoConsultation BIT NOT NULL,
    Status NVARCHAR(40) NOT NULL,
    Reason NVARCHAR(500) NOT NULL
);

CREATE INDEX IX_Appointments_Doctor_Time ON Appointments(DoctorId, StartsAt, EndsAt)
WHERE Status IN ('Pending', 'Confirmed', 'InProgress');

CREATE TABLE Prescriptions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PatientId UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL REFERENCES Doctors(Id),
    IssuedAt DATETIMEOFFSET NOT NULL,
    Notes NVARCHAR(1000) NULL
);

CREATE TABLE PrescriptionItems (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PrescriptionId UNIQUEIDENTIFIER NOT NULL REFERENCES Prescriptions(Id),
    Medication NVARCHAR(240) NOT NULL,
    Dosage NVARCHAR(120) NULL,
    Frequency NVARCHAR(120) NULL
);

CREATE TABLE LabReports (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PatientId UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(Id),
    TestName NVARCHAR(180) NOT NULL,
    Status NVARCHAR(40) NOT NULL,
    OrderedAt DATETIMEOFFSET NOT NULL,
    ReportedAt DATETIMEOFFSET NULL,
    ResultSummary NVARCHAR(MAX) NULL
);

CREATE TABLE Invoices (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PatientId UNIQUEIDENTIFIER NOT NULL REFERENCES Patients(Id),
    Amount DECIMAL(18, 2) NOT NULL,
    Currency CHAR(3) NOT NULL,
    Status NVARCHAR(40) NOT NULL,
    InsuranceClaimStatus NVARCHAR(60) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE EmergencyCases (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BranchId UNIQUEIDENTIFIER NOT NULL REFERENCES Branches(Id),
    PatientName NVARCHAR(180) NOT NULL,
    Severity NVARCHAR(40) NOT NULL,
    Location NVARCHAR(240) NOT NULL,
    Status NVARCHAR(40) NOT NULL,
    ReportedAt DATETIMEOFFSET NOT NULL
);

CREATE TABLE AuditEntries (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OccurredAt DATETIMEOFFSET NOT NULL,
    Actor NVARCHAR(255) NOT NULL,
    Action NVARCHAR(120) NOT NULL,
    Resource NVARCHAR(120) NOT NULL,
    Metadata NVARCHAR(MAX) NULL
);
